// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwduaysywemwapfazfwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3ZHVheXN5d2Vtd2FwZmF6ZndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzgyMjEsImV4cCI6MjA2MzMxNDIyMX0.07djNRBl57QuzgauW4hO15678A3g44YfrGexm3dGkSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);